## Code Description and Objective

This script is part of a set of web scraping scripts developed to consolidate key information into a robust dataset focused on the real estate market. The dataset is designed to provide strategic insights that support investment decision-making by analyzing trends and economic data related to the real estate sector.

This particular script automates the collection of Euribor rates for the strategic months of June and November each year. These rates are crucial for understanding the dynamics of the credit market, a cornerstone of real estate market.

In [1]:
from scripts import get_euribor_annual_rates as euribor

In [2]:
euribor.get_euribor_annual_rates(10)

Fetching data for the year 2015...
Fetching data for the year 2016...
Fetching data for the year 2017...
Fetching data for the year 2018...
Fetching data for the year 2019...
Fetching data for the year 2020...
Fetching data for the year 2021...
Fetching data for the year 2022...
Fetching data for the year 2023...
Fetching data for the year 2024...

The generated DataFrame was saved as 'df_euribor'
The CSV file was saved at: #filepath

DataFrame successfully generated! Displaying first rows:

   Year  Month  Annual Euribor Rate
0  2024     11                2.629
1  2024      6                3.722
2  2023     11                4.044
3  2023      6                3.875
4  2022     11                2.686

    Year  Month  Annual Euribor Rate
0   2024     11                2.629
1   2024      6                3.722
2   2023     11                4.044
3   2023      6                3.875
4   2022     11                2.686
5   2022      6                0.417
6   2021     11               -0.443
7   2021      6               -0.487
8   2020     11               -0.486
9   2020      6               -0.103
10  2019     11               -0.281
11  2019      6               -0.175
12  2018     11               -0.148
13  2018      6               -0.184
14  2017     11               -0.187
15  2017      6               -0.131
16  2016     11               -0.069
17  2016      6               -0.018
18  2015     11                0.109
19  2015      6                0.161